"""阶段生成器与 Pipeline 标准状态之间的适配层。

本模块负责：
- 将全局 config + 上一阶段结果转换为某阶段 generate_* 所需的局部配置；
- 将真实阶段生成器输出标准化为 pipeline 使用的 stage_X_result；
- 显式处理 MA/kA、Vs/Wb 字段差异；
- 提供 Stage 2 → Stage 3 的真实生成器适配。
"""

from __future__ import annotations

from typing import Any

COIL_NAMES = ("CS1", "CS2", "CS3", "PF1", "PF2", "PF3", "PF4", "Div1", "Div2", "VS")


def ma_to_ka(value_ma: float) -> float:
    """MA 转 kA。"""

    return float(value_ma) * 1000.0


def ka_to_ma(value_ka: float) -> float:
    """kA 转 MA。"""

    return float(value_ka) / 1000.0


def coil_state_ma_to_ka(coil_state_ma: dict[str, Any]) -> dict[str, float]:
    """线圈状态 MA → kA。"""

    return {name: ma_to_ka(float(coil_state_ma.get(name, 0.0))) for name in COIL_NAMES}


def coil_state_ka_to_ma(coil_state_ka: dict[str, Any]) -> dict[str, float]:
    """线圈状态 kA → MA。"""

    return {name: ka_to_ma(float(coil_state_ka.get(name, 0.0))) for name in COIL_NAMES}


def build_stage_2_config_from_global(config: dict[str, Any], stage_1_result: dict[str, Any]) -> dict[str, Any]:
    """由全局输入和 Stage 1 末态构造 Stage 2 局部配置。"""

    timeline = config["timeline"]
    target = config["target"]
    shape = target.get("shape", {})
    constraints = config.get("constraints", {})
    device = config.get("device", {})
    options = config.get("options", {})
    physics = config.get("physics", {})

    start_time = float(timeline["breakdown_end_s"])
    end_time = float(timeline["rampup_end_s"])
    start_ip = float(stage_1_result["Ip_at_breakdown_end_MA"])
    target_ip = float(target["Ip_flat_MA"])
    duration = max(end_time - start_time, 1.0e-9)
    mid_time = start_time + 0.50 * duration

    initial_shape = _initial_rampup_shape(config)
    target_shape = {
        "major_radius_m": float(shape.get("R_axis_m", device.get("R0_m", 1.85))),
        "minor_radius_m": float(shape.get("minor_radius_m", device.get("a_m", 0.57))),
        "elongation": float(shape.get("kappa_flat", 1.75)),
        "triangularity": float(shape.get("delta_flat", 0.35)),
        "vertical_position_m": float(shape.get("vertical_position_m", 0.0)),
    }

    coil_limits = _build_stage_2_coil_limits(config)
    total_flux = _stage_2_total_flux_budget(config)
    already_consumed = float(stage_1_result.get("cs_flux_used_breakdown_Vs", 0.0))

    return {
        "metadata": {
            "case_id": f"{config.get('case_name', 'unnamed_case')}_stage_2_rampup",
            "stage": "rampup",
            "description": "Pipeline-generated Stage 2 config from Stage 1 handoff.",
            "version": "0.2.0",
        },
        "device": {
            "name": device.get("name", "SPARC_simplified"),
            "B0_T": float(device.get("B0_T", 12.2)),
            "R0_m": float(device.get("R0_m", 1.85)),
            "a_m": float(device.get("a_m", 0.57)),
        },
        "handoff_from_stage_1": {
            "source_stage": "breakdown",
            "source_case_id": config.get("case_name", "unnamed_case"),
            "time_s": start_time,
            "plasma_current_MA": start_ip,
            "loop_voltage_V": float(constraints.get("breakdown_loop_voltage_V", 0.0)),
            "flux_consumed_Wb": already_consumed,
            "plasma_state": {
                "breakdown_success": bool(stage_1_result.get("breakdown_validation", {}).get("passed", False)),
                "electron_temperature_eV": float(_nested_get(physics, ("stage_2", "plasma_resistance", "Te_start_eV"), 80.0)),
                "line_average_density_1e19_m3": 0.15,
                **initial_shape,
            },
            "coil_currents_kA": coil_state_ma_to_ka(stage_1_result.get("coil_state_at_breakdown_end", {})),
            "notes": ["Generated by common.adapters.build_stage_2_config_from_global."],
        },
        "targets": {
            "end_time_s": end_time,
            "target_plasma_current_MA": target_ip,
            "target_loop_voltage_V": float(target.get("target_loop_voltage_V", 1.2)),
            "target_q95": float(target.get("q95", target.get("target_q95", 3.2))),
            "max_flux_consumption_Wb": float(_nested_get(physics, ("stage_2", "max_flux_consumption_Wb"), total_flux)),
            "target_shape": target_shape,
        },
        "waveform_strategy": {
            "time_grid": {
                "start_time_s": start_time,
                "end_time_s": end_time,
                "step_s": float(timeline.get("dt_s", 0.02)),
            },
            "current_ramp": {
                "mode": "smooth_piecewise_linear",
                "max_ramp_rate_MA_per_s": _stage_2_ip_ramp_limit(config, start_ip, target_ip, duration),
                "breakpoints": [
                    {"time_s": start_time, "plasma_current_MA": start_ip},
                    {"time_s": end_time, "plasma_current_MA": target_ip},
                ],
            },
            "loop_voltage_profile": {
                "mode": "computed_from_plasma_circuit",
                "initial_voltage_V": float(constraints.get("breakdown_loop_voltage_V", 20.0)),
                "final_voltage_V": float(target.get("target_loop_voltage_V", 1.2)),
                "max_voltage_V": float(_nested_get(physics, ("stage_2", "max_loop_voltage_V"), 500.0)),
                "min_voltage_V": 0.0,
            },
            "shape_evolution": {
                "mode": "smooth_to_target",
                "preserve_axis_radius": True,
            },
            "density_ramp": {
                "mode": "proportional_to_current",
                "start_line_average_density_1e19_m3": 0.15,
                "end_line_average_density_1e19_m3": float(_nested_get(physics, ("stage_2", "density_end_1e19_m3"), 4.0)),
                "max_rate_1e19_m3_per_s": 5.0,
            },
        },
        "engineering_limits": {
            "flux": {
                "total_available_Wb": total_flux,
                "already_consumed_Wb": already_consumed,
                "max_stage_2_consumption_Wb": float(_nested_get(physics, ("stage_2", "max_stage_2_consumption_Wb"), total_flux)),
            },
            "loop_voltage": {
                "min_V": 0.0,
                "max_V": float(_nested_get(physics, ("stage_2", "max_loop_voltage_V"), 500.0)),
            },
            "plasma_current": {
                "min_MA": 0.0,
                "max_MA": max(target_ip * 1.05, target_ip + 0.1),
                "max_ramp_rate_MA_per_s": _stage_2_ip_ramp_limit(config, start_ip, target_ip, duration),
            },
            "coil_currents": coil_limits,
            "power_supplies": {
                "max_voltage_V": {"CS": 1200.0, "PF": 800.0},
                "max_power_MW": {"total": 250.0},
            },
        },
        "physics_constraints": {
            "q95": {"min": float(_nested_get(physics, ("stage_2", "q95_min"), 2.3)), "target": 3.2},
            "internal_inductance": {"min": 0.55, "max": 1.20},
            "normalized_beta": {"max": 1.8},
            "vertical_stability": {"min_margin": 0.15},
            "flux_margin": {"min_fraction": float(constraints.get("min_cs_flux_margin_fraction", 0.10))},
            "pf_balance": {"max_residual": float(_nested_get(physics, ("stage_2", "pf_balance_max_residual"), 20.0))},
            "plasma_shape": {
                "elongation": {"min": 1.0, "max": max(2.2, target_shape["elongation"] + 0.1)},
                "triangularity": {"min": -0.05, "max": max(0.6, target_shape["triangularity"] + 0.1)},
                "minor_radius_m": {"min": 0.20, "max": max(0.75, target_shape["minor_radius_m"] + 0.1)},
            },
        },
        "physics": _build_stage_2_physics(config),
        "control_constraints": {
            "controller_update_period_s": 0.005,
            "waveform_sample_period_s": float(timeline.get("dt_s", 0.02)),
            "vs_reserved_fraction": float(config.get("coils", {}).get("VS", {}).get("reserved_fraction", 0.20)),
            "tracking_tolerances": {
                "plasma_current_MA": 0.05,
                "loop_voltage_V": float(_nested_get(physics, ("stage_2", "loop_voltage_tolerance_V"), 2.0)),
                "coil_current_kA": 0.25,
                "shape_dimension_m": 0.01,
            },
            "fallback_behavior": {
                "on_constraint_warning": "continue_with_warning",
                "on_constraint_violation": "stop_and_report",
            },
        },
        "outputs": {
            "requested": ["summary", "waveforms", "constraint_report", "handoff_to_stage_3"],
            "waveform_channels": ["time_s", "plasma_current_MA", "loop_voltage_V", "flux_consumed_Wb", "q95"],
            "handoff_to_stage_3_fields": ["time_s", "plasma_current_MA", "flux_remaining_Wb", "target_shape", "coil_currents_kA"],
        },
        "validation": {
            "require_stage_1_handoff": True,
            "require_monotonic_time": True,
            "require_monotonic_current_ramp": True,
            "allow_warnings": True,
            "fail_on_limit_violation": True,
        },
    }


def normalize_stage_2_result_for_pipeline(raw_result: dict[str, Any], config: dict[str, Any], stage_1_result: dict[str, Any]) -> dict[str, Any]:
    """将 Stage 2 真实生成器输出标准化为 pipeline 的 stage_2_result。"""

    summary = raw_result.get("summary", {})
    validation = raw_result.get("rampup_validation", {})
    handoff = raw_result.get("handoff_to_stage_3", {})
    coil_state_ma = coil_state_ka_to_ma(raw_result.get("coil_state_at_rampup_end", {}))
    shape_state = _normalize_stage_2_shape_state(raw_result.get("shape_state_at_rampup_end", {}), config)

    return {
        "stage_name": "rampup",
        "execution_mode": "stage_generator",
        "time_range_s": {
            "start": float(summary.get("start_time_s", config["timeline"]["breakdown_end_s"])),
            "end": float(summary.get("end_time_s", config["timeline"]["rampup_end_s"])),
        },
        "Ip_at_rampup_start_MA": float(summary.get("start_plasma_current_MA", stage_1_result["Ip_at_breakdown_end_MA"])),
        "Ip_at_rampup_end_MA": float(summary.get("end_plasma_current_MA", config["target"]["Ip_flat_MA"])),
        "coil_state_at_rampup_start": stage_1_result.get("coil_state_at_breakdown_end", {}),
        "coil_state_at_rampup_end": coil_state_ma,
        "shape_state_at_rampup_end": shape_state,
        "cs_flux_used_rampup_Vs": round(float(summary.get("stage_2_flux_consumed_Wb", 0.0)), 6),
        "cs_flux_remaining_after_rampup_Vs": round(float(handoff.get("flux_remaining_Wb", raw_result.get("cs_flux_remaining_after_rampup_Wb", 0.0))), 6),
        "physics_diagnostics": raw_result.get("physics_diagnostics", {}),
        "handoff_to_stage_3": handoff,
        "raw_stage_result_summary": summary,
        "waveform_rows": raw_result.get("rampup_waveform", []),
        "waveform_ref": f"outputs/{config.get('case_name', 'unnamed_case')}/stage_2_rampup_waveform.csv",
        "rampup_validation": validation,
    }


def build_stage_3_config_from_stage_2_result(config: dict[str, Any], stage_2_result: dict[str, Any]) -> dict[str, Any]:
    """由全局输入和 Stage 2 末态构造 Stage 3 局部配置。"""

    timeline = config["timeline"]
    target = config["target"]
    shape = target.get("shape", {})
    device = config.get("device", {})
    constraints = config.get("constraints", {})
    physics = config.get("physics", {})
    stage_3_physics = physics.get("stage_3", {}) if isinstance(physics.get("stage_3", {}), dict) else {}
    start_time = float(timeline["rampup_end_s"])
    end_time = float(timeline["flattop_end_s"])
    total_flux = float(_nested_get(stage_3_physics, ("total_available_Wb",), max(constraints.get("cs_flux_budget_Vs", 35.0), 120.0)))
    already_consumed = total_flux - float(stage_2_result.get("cs_flux_remaining_after_rampup_Vs", 0.0))
    target_shape = _stage_3_target_shape(config)

    return {
        "metadata": {"case_id": f"{config.get('case_name', 'unnamed_case')}_stage_3_flattop", "stage": "flattop", "description": "Pipeline-generated Stage 3 config from Stage 2 handoff.", "version": "0.2.0"},
        "device": {"name": device.get("name", "SPARC_simplified"), "B0_T": float(device.get("B0_T", 12.2)), "R0_m": float(device.get("R0_m", 1.85)), "a_m": float(device.get("a_m", 0.57))},
        "handoff_from_stage_2": {
            "source_stage": "rampup",
            "source_case_id": config.get("case_name", "unnamed_case"),
            "time_s": start_time,
            "plasma_current_MA": float(stage_2_result.get("Ip_at_rampup_end_MA", target["Ip_flat_MA"])),
            "loop_voltage_V": float(stage_2_result.get("handoff_to_stage_3", {}).get("loop_voltage_V", target.get("target_loop_voltage_V", 1.0))),
            "flux_consumed_Wb": already_consumed,
            "flux_remaining_Wb": float(stage_2_result.get("cs_flux_remaining_after_rampup_Vs", total_flux - already_consumed)),
            "q95": float(stage_2_result.get("handoff_to_stage_3", {}).get("q95", target.get("target_q95", 3.2))),
            "internal_inductance": float(stage_2_result.get("handoff_to_stage_3", {}).get("internal_inductance", 0.78)),
            "vertical_stability_margin": float(stage_2_result.get("handoff_to_stage_3", {}).get("vertical_stability_margin", 0.35)),
            "physics_diagnostics": stage_2_result.get("physics_diagnostics", {}),
            "target_shape": target_shape,
            "coil_currents_kA": coil_state_ma_to_ka(stage_2_result.get("coil_state_at_rampup_end", {})),
            "constraint_status": {"stage_2_status": "passed" if stage_2_result.get("rampup_validation", {}).get("passed", False) else "warning"},
        },
        "targets": {"end_time_s": end_time, "target_plasma_current_MA": float(target["Ip_flat_MA"]), "allowed_current_deviation_MA": float(_nested_get(stage_3_physics, ("allowed_current_deviation_MA",), 0.05)), "target_loop_voltage_V": float(_nested_get(stage_3_physics, ("target_loop_voltage_V",), 0.8)), "target_q95": float(target.get("target_q95", target.get("q95", 3.2))), "max_flux_consumption_Wb": float(_nested_get(stage_3_physics, ("max_flux_consumption_Wb",), 15.0)), "min_flux_margin_fraction": float(constraints.get("min_cs_flux_margin_fraction", 0.15)), "target_shape": target_shape, "divertor_targets": _stage_3_divertor_targets(shape)},
        "waveform_strategy": {"time_grid": {"start_time_s": start_time, "end_time_s": end_time, "step_s": float(timeline.get("dt_s", 0.02))}, "plasma_current_hold": {"mode": "constant_with_small_tolerance", "smoothing_time_s": 0.20}, "loop_voltage_profile": {"mode": "computed_from_plasma_circuit"}, "cs_maintenance": {"mode": "mutual_inductance_hold", "distribute_to_coils": physics.get("cs_swing_share", config.get("options", {}).get("cs_swing_share", {}))}, "pf_shape_hold": {"mode": "response_matrix_hold"}, "divertor_control": {"mode": "response_matrix_small_sweep", "base_currents_kA": {"Div1": 0.0, "Div2": 0.0}}, "vs_reserve": {"mode": "reserve_range_only", "baseline_current_kA": 0.0, "reserve_fraction_of_limit": float(config.get("coils", {}).get("VS", {}).get("reserved_fraction", 0.70))}},
        "engineering_limits": {"flux": {"total_available_Wb": total_flux, "already_consumed_Wb": already_consumed, "remaining_at_stage_start_Wb": float(stage_2_result.get("cs_flux_remaining_after_rampup_Vs", 0.0)), "max_stage_3_consumption_Wb": float(_nested_get(stage_3_physics, ("max_stage_3_consumption_Wb",), 15.0)), "min_remaining_fraction_at_end": float(constraints.get("min_cs_flux_margin_fraction", 0.15))}, "loop_voltage": {"min_V": 0.0, "max_V": float(_nested_get(stage_3_physics, ("max_loop_voltage_V",), 2.5))}, "plasma_current": {"min_MA": float(target["Ip_flat_MA"]) - 0.2, "max_MA": float(target["Ip_flat_MA"]) + 0.2, "max_deviation_from_target_MA": 0.05}, "coil_currents": _build_stage_3_coil_limits(config), "power_supplies": {"max_voltage_V": {"CS": 600.0, "PF": 500.0, "Div": 250.0, "VS": 800.0}, "max_power_MW": {"total": 180.0}}},
        "physics": _build_stage_3_physics(config),
        "physics_constraints": {"q95": {"min": 2.8, "target": 3.2}, "internal_inductance": {"min": 0.55, "max": 1.20}, "normalized_beta": {"max": 1.8}, "density": {"line_average_density_1e20_m3": {"target": 4.0, "min": 3.5, "max": 4.5}}, "vertical_stability": {"min_margin": 0.18, "require_vs_reserve": True}, "plasma_shape": {"major_radius_m": {"target": target_shape["major_radius_m"], "tolerance": 0.02}, "minor_radius_m": {"target": target_shape["minor_radius_m"], "min": max(0.1, target_shape["minor_radius_m"] - 0.05), "max": target_shape["minor_radius_m"] + 0.05}, "elongation": {"target": target_shape["elongation"], "min": target_shape["elongation"] - 0.15, "max": target_shape["elongation"] + 0.15}, "triangularity": {"target": target_shape["triangularity"], "min": target_shape["triangularity"] - 0.15, "max": target_shape["triangularity"] + 0.15}, "vertical_position_m": {"target": 0.0, "tolerance": 0.02}}, "divertor": {"require_x_point": True, "max_strike_point_error_m": 0.04, "max_sweep_amplitude_m": 0.03}},
        "control_constraints": {"controller_update_period_s": 0.005, "waveform_sample_period_s": float(timeline.get("dt_s", 0.02)), "tracking_tolerances": {"plasma_current_MA": 0.05, "loop_voltage_V": 0.3, "coil_current_kA": 0.20, "shape_dimension_m": 0.01, "x_point_position_m": 0.03, "strike_point_position_m": 0.04}, "fallback_behavior": {"on_constraint_warning": "continue_with_warning", "on_constraint_violation": "stop_and_report"}},
        "outputs": {"requested": ["summary", "waveforms", "constraint_report", "final_state", "revision_suggestions"]},
        "validation": {"require_stage_2_handoff": True, "require_monotonic_time": True, "require_current_hold_within_tolerance": True, "require_flux_margin": True, "allow_warnings": True, "fail_on_limit_violation": True},
    }


def normalize_stage_3_result_for_pipeline(raw_result: dict[str, Any], config: dict[str, Any], stage_2_result: dict[str, Any]) -> dict[str, Any]:
    """将 Stage 3 真实生成器输出标准化为 pipeline 的 stage_3_result。"""

    summary = raw_result.get("summary", {})
    final_state = raw_result.get("final_state", {})
    return {
        "stage_name": "flattop",
        "execution_mode": "stage_generator",
        "time_range_s": {"start": float(summary.get("start_time_s", config["timeline"]["rampup_end_s"])), "end": float(summary.get("end_time_s", config["timeline"]["flattop_end_s"]))},
        "Ip_at_flattop_start_MA": float(stage_2_result.get("Ip_at_rampup_end_MA", config["target"]["Ip_flat_MA"])),
        "Ip_at_flattop_end_MA": float(final_state.get("plasma_current_MA", config["target"]["Ip_flat_MA"])),
        "coil_state_at_flattop_start": stage_2_result.get("coil_state_at_rampup_end", {}),
        "coil_state_at_flattop_end": coil_state_ka_to_ma(raw_result.get("coil_state_at_flattop_end", {})),
        "shape_state_at_flattop_end": final_state.get("shape", raw_result.get("shape_state_at_flattop_end", {})),
        "cs_flux_used_flattop_Vs": round(float(summary.get("stage_3_flux_consumed_Wb", 0.0)), 6),
        "cs_flux_margin": {"remaining_Vs": round(float(summary.get("flux_remaining_Wb", 0.0)), 6), "margin_fraction": round(float(summary.get("flux_margin_fraction", 0.0)), 6), "passed": bool(raw_result.get("flattop_validation", {}).get("passed", False))},
        "divertor_setting": raw_result.get("auxiliary_settings", {}).get("divertor_setting", {}),
        "vs_reserved_range": raw_result.get("auxiliary_settings", {}).get("vs_reserved_range_kA", {}),
        "physics_diagnostics": final_state.get("physics_diagnostics", {}),
        "raw_stage_result_summary": summary,
        "waveform_rows": raw_result.get("flattop_waveform", []),
        "waveform_ref": f"outputs/{config.get('case_name', 'unnamed_case')}/stage_3_flattop_waveform.csv",
        "flattop_validation": raw_result.get("flattop_validation", {}),
    }


def _initial_rampup_shape(config: dict[str, Any]) -> dict[str, float]:
    device = config.get("device", {})
    return {
        "major_radius_m": float(device.get("R0_m", 1.85)),
        "minor_radius_m": max(0.30, 0.60 * float(device.get("a_m", 0.57))),
        "elongation": 1.15,
        "triangularity": 0.05,
        "vertical_position_m": 0.0,
    }


def _normalize_stage_2_shape_state(raw_shape: dict[str, Any], config: dict[str, Any]) -> dict[str, Any]:
    shape = config.get("target", {}).get("shape", {})
    return {
        "R_axis_m": float(raw_shape.get("major_radius_m", shape.get("R_axis_m", config.get("device", {}).get("R0_m", 0.0)))),
        "minor_radius_m": float(raw_shape.get("minor_radius_m", shape.get("minor_radius_m", config.get("device", {}).get("a_m", 0.0)))),
        "kappa": float(raw_shape.get("elongation", shape.get("kappa_flat", 0.0))),
        "delta": float(raw_shape.get("triangularity", shape.get("delta_flat", 0.0))),
        "vertical_position_m": float(raw_shape.get("vertical_position_m", 0.0)),
        "x_point": shape.get("x_point", "unspecified"),
    }


def _build_stage_2_coil_limits(config: dict[str, Any]) -> dict[str, dict[str, float]]:
    coils = config.get("coils", {})
    physics = config.get("physics", {})
    stage_2_limits = physics.get("stage_2", {}).get("coil_limits_kA", {}) if isinstance(physics.get("stage_2", {}), dict) else {}
    result: dict[str, dict[str, float]] = {}
    for name in COIL_NAMES:
        coil = coils.get(name, {})
        if name in stage_2_limits:
            configured = stage_2_limits[name]
            result[name] = {
                "min_kA": float(configured.get("min_kA", ma_to_ka(coil.get("I_min_MA", -10.0)))),
                "max_kA": float(configured.get("max_kA", ma_to_ka(coil.get("I_max_MA", 10.0)))),
                "max_slew_rate_kA_per_s": float(configured.get("max_slew_rate_kA_per_s", ma_to_ka(coil.get("dI_dt_max_MA_per_s", 10.0)))),
            }
            continue

        scale = 1000.0
        result[name] = {
            "min_kA": ma_to_ka(float(coil.get("I_min_MA", -10.0))) * scale,
            "max_kA": ma_to_ka(float(coil.get("I_max_MA", 10.0))) * scale,
            "max_slew_rate_kA_per_s": ma_to_ka(float(coil.get("dI_dt_max_MA_per_s", 10.0))) * scale,
        }
    return result


def _build_stage_2_physics(config: dict[str, Any]) -> dict[str, Any]:
    physics = config.get("physics", {})
    stage_2 = physics.get("stage_2", {}) if isinstance(physics.get("stage_2", {}), dict) else {}
    return {
        "cs_mutual_inductance_H": stage_2.get("cs_mutual_inductance_H", physics.get("cs_mutual_inductance_H", {})),
        "cs_swing_share": stage_2.get("cs_swing_share", config.get("options", {}).get("cs_swing_share", {})),
        "plasma_resistance": stage_2.get(
            "plasma_resistance",
            {
                "mode": "endpoint_power_law",
                "R_start_ohm": 1.0e-4,
                "R_end_ohm": 1.0e-6,
                "Te_start_eV": 80.0,
                "Te_end_eV": 2000.0,
            },
        ),
        "internal_inductance": stage_2.get("internal_inductance", {"start": 0.95, "end": 0.75}),
        "poloidal_beta": stage_2.get("poloidal_beta", {"start": 0.05, "end": 0.25}),
        "pf_response_matrix": stage_2.get(
            "pf_response_matrix",
            {
                "rows": ["Bv", "Br", "G_kappa", "G_delta", "G_Z"],
                "columns": ["PF1", "PF2", "PF3", "PF4"],
                "values": [
                    [0.002, 0.004, 0.010, 0.018],
                    [0.001, -0.001, 0.004, 0.000],
                    [0.020, 0.030, 0.006, 0.002],
                    [0.004, 0.018, 0.010, 0.002],
                    [0.001, -0.001, 0.006, 0.001],
                ],
            },
        ),
        "pf_shape_gains": stage_2.get("pf_shape_gains", {"kappa": 0.02, "triangularity": 0.015, "vertical_position": 0.02}),
        "solver": stage_2.get(
            "solver",
            {
                "pf_regularization": 0.01,
                "weights": {"Bv": 1.0, "Br": 0.5, "G_kappa": 0.8, "G_delta": 0.8, "G_Z": 0.5},
            },
        ),
    }


def _stage_2_total_flux_budget(config: dict[str, Any]) -> float:
    constraints = config.get("constraints", {})
    physics = config.get("physics", {})
    configured = _nested_get(physics, ("stage_2", "total_available_Wb"), None)
    if configured is not None:
        return float(configured)
    return max(float(constraints.get("cs_flux_budget_Vs", 35.0)), 600.0)


def _stage_2_ip_ramp_limit(config: dict[str, Any], start_ip: float, target_ip: float, duration: float) -> float:
    physics = config.get("physics", {})
    configured = _nested_get(physics, ("stage_2", "max_ramp_rate_MA_per_s"), None)
    if configured is not None:
        return float(configured)
    average_rate = abs(target_ip - start_ip) / max(duration, 1.0e-9)
    return max(average_rate * 1.5, 6.0)


def _stage_3_target_shape(config: dict[str, Any]) -> dict[str, Any]:
    shape = config.get("target", {}).get("shape", {})
    device = config.get("device", {})
    x_point = shape.get("x_point", {})
    if not isinstance(x_point, dict):
        x_point = {"enabled": True, "lower_x_point": {"R_m": 1.55, "Z_m": -1.05}}
    return {"major_radius_m": float(shape.get("R_axis_m", device.get("R0_m", 1.85))), "minor_radius_m": float(shape.get("minor_radius_m", device.get("a_m", 0.57))), "elongation": float(shape.get("kappa_flat", 1.75)), "triangularity": float(shape.get("delta_flat", 0.35)), "vertical_position_m": float(shape.get("vertical_position_m", 0.0)), "x_point": x_point}


def _stage_3_divertor_targets(shape: dict[str, Any]) -> dict[str, Any]:
    return {"mode": "fixed_or_small_sweep", "strike_point_lower_outer": {"R_m": 1.72, "Z_m": -1.18, "tolerance_m": 0.04}, "strike_point_lower_inner": {"R_m": 1.22, "Z_m": -1.10, "tolerance_m": 0.04}, "allow_sweep": True, "sweep_amplitude_m": 0.01, "sweep_period_s": 1.0}


def _build_stage_3_coil_limits(config: dict[str, Any]) -> dict[str, dict[str, float]]:
    coils = config.get("coils", {})
    result: dict[str, dict[str, float]] = {}
    for name in COIL_NAMES:
        coil = coils.get(name, {})
        result[name] = {"min_kA": ma_to_ka(float(coil.get("I_min_MA", -10.0))), "max_kA": ma_to_ka(float(coil.get("I_max_MA", 10.0))), "max_slew_rate_kA_per_s": ma_to_ka(float(coil.get("dI_dt_max_MA_per_s", 10.0)))}
    return result


def _build_stage_3_physics(config: dict[str, Any]) -> dict[str, Any]:
    physics = config.get("physics", {})
    stage_3 = physics.get("stage_3", {}) if isinstance(physics.get("stage_3", {}), dict) else {}
    return {"device": {"B0_T": float(config.get("device", {}).get("B0_T", 12.2)), "R0_m": float(config.get("device", {}).get("R0_m", 1.85)), "a_m": float(config.get("device", {}).get("a_m", 0.57))}, "cs_mutual_inductance_H": stage_3.get("cs_mutual_inductance_H", {"CS1": 1.2e-3, "CS2": 1.5e-3, "CS3": 1.2e-3}), "cs_swing_share": stage_3.get("cs_swing_share", config.get("options", {}).get("cs_swing_share", {})), "plasma_resistance": stage_3.get("plasma_resistance", {"mode": "hold_with_small_variation", "R_flat_ohm": 1.0e-7, "variation_fraction": 0.10, "Te_flat_eV": 3000.0}), "internal_inductance": stage_3.get("internal_inductance", {"flat": 0.78, "ripple_amplitude": 0.01}), "poloidal_beta": stage_3.get("poloidal_beta", {"flat": 0.35, "ripple_amplitude": 0.02}), "pf_response_matrix": stage_3.get("pf_response_matrix", {"rows": ["Bv", "Br", "G_kappa", "G_delta", "G_Z", "G_X"], "columns": ["PF1", "PF2", "PF3", "PF4"], "values": [[0.002, 0.004, 0.010, 0.018], [0.001, -0.001, 0.004, 0.000], [0.020, 0.030, 0.006, 0.002], [0.004, 0.018, 0.010, 0.002], [0.001, -0.001, 0.006, 0.001], [0.002, 0.005, 0.008, 0.003]]}), "div_response_matrix": stage_3.get("div_response_matrix", {"rows": ["strike_R", "strike_Z"], "columns": ["Div1", "Div2"], "values": [[0.020, -0.015], [0.010, 0.010]]}), "pf_shape_gains": stage_3.get("pf_shape_gains", {"kappa": 0.02, "triangularity": 0.015, "vertical_position": 0.02, "x_point": 0.02}), "solver": stage_3.get("solver", {"pf_regularization": 0.01, "div_regularization": 0.01, "weights": {"Bv": 1.0, "Br": 0.5, "G_kappa": 0.8, "G_delta": 0.8, "G_Z": 0.6, "G_X": 0.7}})}


def _nested_get(mapping: dict[str, Any], keys: tuple[str, ...], default: Any) -> Any:
    current: Any = mapping
    for key in keys:
        if not isinstance(current, dict) or key not in current:
            return default
        current = current[key]
    return current
